// Rasterizes brand/icon.svg into the app icons electron-builder + the web app need:
//   apps/desktop/build/icon.png  (1024) -> used to derive .icns on mac
//   apps/desktop/build/icon.ico  (multi-size Windows icon)
//   apps/web/public/icon-512.png, favicon assets
// Requires sharp + png-to-ico (root devDependencies).
import sharp from "sharp";
import pngToIco from "png-to-ico";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const svg = resolve(root, "brand", "icon.svg");

const desktopBuild = resolve(root, "apps", "desktop", "build");
const webPublic = resolve(root, "apps", "web", "public");
mkdirSync(desktopBuild, { recursive: true });
mkdirSync(webPublic, { recursive: true });

if (!existsSync(svg)) {
  console.error("[icons] Source not found:", svg);
  process.exit(1);
}

async function png(size, outPath) {
  await sharp(svg, { density: 384 }).resize(size, size).png().toFile(outPath);
  return outPath;
}

const main = async () => {
  console.log("[icons] Rendering PNGs from", svg);
  await png(1024, resolve(desktopBuild, "icon.png"));     // mac/linux master
  await png(512, resolve(webPublic, "icon-512.png"));     // web PWA / og
  await png(192, resolve(webPublic, "icon-192.png"));
  const fav = await png(64, resolve(webPublic, "favicon-64.png"));

  console.log("[icons] Building Windows .ico");
  const sizes = await Promise.all(
    [16, 24, 32, 48, 64, 128, 256].map((s) =>
      sharp(svg, { density: 384 }).resize(s, s).png().toBuffer()
    )
  );
  const ico = await pngToIco(sizes);
  writeFileSync(resolve(desktopBuild, "icon.ico"), ico);

  console.log("[icons] Done.", fav);
  console.log("[icons] Note: macOS .icns is generated by electron-builder from icon.png on mac/CI.");
};

main().catch((e) => {
  console.error("[icons] Failed:", e);
  process.exit(1);
});
